//   @NORMAL：不改变referer
//   @FORGE：发送根站点referer
//   @ORIGINAL：发送打开站点referer
//   @BLOCK : 发送空referer

//2014.11.25 增加chiphell,niunews
//2014.11.09 增加pconline和postimg
//2014.10.27

sites = {
    //自定义
    'about:blank': '@NORMAL',
    'jump.bdimg.com': '@NORMAL',
    'img.liufen.com': 'http://www.liufen.com.cn/',
    't4.mangafiles.com' : 'http://www.imanhua.com/',
    't5.mangafiles.com' : 'http://www.imanhua.com/',
    'laibafile.cn' : 'http://www.tianya.cn/',
    'zol.com.cn' : '@FORGE',
    'tmoke.com': '@BLOCK',
    '51img1.com' : '@FORGE',
    'zol-img.com.cn' : '@FORGE',
    'pconline.com.cn': '@FORGE',
    'postimg.org': '@FORGE',
    'chiphell.com': '@FORGE',
    'niunews.cn': '@FORGE',
    'mp3cube.net': '@FORGE',
    // 
    'douban.com': 'http://www.douban.com',
    'yyets.com': 'http://www.yyets.com/',
    'img.cnbeta.com': '@FORGE',
     
    // baidu 相关网站
    'hiphotos.baidu.com': '@FORGE',
    'hiphotos.bdimg.com' : '@FORGE',
    'imgsrc.baidu.com': '@FORGE',
    'baidu-img.cn': 'http://www.baidu.com/',

    // sina
    'photo.sina.com.cn': '@BLOCK',
    'sinaimg.cn': 'http://blog.sina.com.cn/',
 
    'pixiv.net': '@FORGE',
    'ph.126.net' : '@FORGE',
    'isnowfy.com': '@FORGE',
    'image.itmedia.co.jp': '@FORGE',
    '2ch.net': '@FORGE',
    'imepita.jp': '@ORIGINAL',
    'tumblr.com': '@FORGE',
    'photo.store.qq.com': '@FORGE',
    'img.pconline.com.cn': '@FORGE',
    'fc2.com': '@BLOCK',
    'blogs.yahoo.co.jp': '@BLOCK',
    'hentaiverse.net': '@BLOCK',
    'qlogo.cn': '@BLOCK',
    'qpic.cn': '@BLOCK',
    'fmn.rrfmn.com': '@BLOCK',
    'postimage.org': '@FORGE',
 
    'bdstatic.com': 'http://tieba.baidu.com/',
    'space.wenxuecity.com': 'http://bbs.wenxuecity.com/',
    'www.autoimg.cn': 'http://club.autohome.com.cn/',
    'kkkmh.com': 'http://www.kkkmh.com/',
    'nonie.1ting.com': 'http://www.1ting.com/',
    'img.knb.im': 'http://www.kenengba.com/',
    'tianya.cn': 'http://bbs.tianya.cn/',
    'xici.net': 'http://www.xici.net/',
    'media.chinagate.com': 'http://www.wenxuecity.com/',
    'jdstatic.tankr.net': 'http://jandan.net/',
    'sankakustatic.com': 'http://chan.sankakucomplex.com/',
    
    'dm5.com' : '@FORGE',
    'rakuten-static.com': '@NORMAL',
    'rakuten.co.jp': '@NORMAL',
    'api.e-map.ne.jp': '@NORMAL',
    '9lala.com' : '@NORMAL',
    '19disk.com' : '@NORMAL', 
    '115cdn.com' : '@NORMAL',
    'space.wenxuecity.com' : 'http://bbs.wenxuecity.com/',
    'yyets.com' : 'http://www.yyets.com/',
    'baidu-img.cn' : 'http://www.baidu.com/',
    'hiphotos.baidu.com' : '@FORGE',
    'forum.fdzone.org' : 'http://forum.fdzone.org/',
    'forum.tw.fdzone.org' : 'http://forum.tw.fdzone.org/',
    'forum.tw2.fdzone.org' : 'http://forum.tw2.fdzone.org/',
    'imageporter.com' : '@FORGE',
    'imageshack.us' : '@FORGE',
    'imgsrc.baidu.com' : '@FORGE',
    'imgur.com' : '@FORGE',
    'myweb.hinet.net' : 'http://myweb.hinet.net/service/download.html?',
    'oversea.forum.fdzone.org' : 'http://oversea.forum.fdzone.org/',
    'tudou.com' : 'http://www.tudou.com/',
    'imgchili.net' : '@NORMAL',
    'imgchili.com' : '@NORMAL',
    'file-static.com' : '@ORIGINAL',
    'static-file.com' : '@ORIGINAL',
    'www.dotup.org' : '@NORMAL',
    '183.60' : '@NORMAL',
    '119.147' : '@NORMAL',
    '112.91' : '@NORMAL',
    '60.221' : '@NORMAL',
    '122.225' : '@NORMAL',
    '218.29' : '@NORMAL',
    '113.105' : '@NORMAL',
    '58.253' : '@NORMAL',
    '211.142' : '@NORMAL',
    '125.211' : '@NORMAL',
    'orzhd.com' : '@NORMAL',
    'img2.sofree.cc' : '@NORMAL',
    'fsm.vip2ch.com' : '@FORGE',
    'turboimagehost.com' : '@NORMAL',
    'imgdino.com' : 'http://imgdino.com/',
    'xindm.cn' : 'http://www.xindm.cn/',
    'img.liufen.com': 'http://www.liufen.com.cn/',
};